Enable Multi level Menus
phpDocumentor/guides pull request #461
Opened 2023-07-05 16:57 UTC by linawolf

To avoid circular relations we need to mark the root document.

depends on #455, which depends on https://github.com/phpDocumentor/guides/pull/443

2023-07-07 12:33 UTC, jaapio commented
@linawolf  please rebase this one, so we can continue with a review :-)

2023-07-09 17:05 UTC, linawolf commented
@jaapio rebased, please review

2023-07-10 19:32 UTC, jaapio requested changes
I think this is good for now, some minor things that need to be addressed before we can merge this. 

---
But as I said on Slack. I think we should have a closer look at what we want to store in the nodes. It feels like they are getting larger and larger every feature we add. But most of the new meta like information that is now stored in the documentnode should not be directly used by the renderer. Which means for me that it should not be in the nodes. It is more like our internal administration that nobody should ever look at. 

During rendering the renderer should basically just look at nodes and child nodes. All properties exposed by the nodes should add value to the rendering. And I think the DocumentEntryNode doesn't do that. We want people to use the menu nodes an not trying to create there own menu tree in the templates to render a menu. 

I think we can address this later.

2023-07-10 19:32 UTC, jaapio commented on packages/guides/src/Compiler/NodeTransformers/TocNodeWithDocumentEntryTransformer.php
> +    public static function isEqualRelativePath(string $actualFile, string $expectedFile, string $currentFile, bool $glob): bool
Please keep these methods private, as they are not used, and should not be used on other locations.

2023-07-10 19:32 UTC, jaapio commented on packages/guides/src/Compiler/NodeTransformers/TocNodeWithDocumentEntryTransformer.php
> +    public static function isEqualAbsolutePath(string $actualFile, string $expectedFile, string $currentFile, bool $glob): bool
Please keep these methods private, as they are not used, and should not be used on other locations.

2023-07-10 19:32 UTC, jaapio commented on packages/guides/src/Compiler/NodeTransformers/TocNodeWithDocumentEntryTransformer.php
> +                if (!$this->isEqualAbsolutePath($documentEntry->getFile(), $file, $currentPath, $glob) && !$this->isEqualRelativePath($documentEntry->getFile(), $file, $currentPath, $glob)) {
isEqualAbsolutePath is static so is isEqualRelativePath. Calls should be `self::` not using `$this`

2023-07-10 19:32 UTC, jaapio commented on packages/guides/src/Handlers/ParseDirectoryHandler.php
> +        $indexName = $this->guardThatAnIndexFileExists(
```suggestion
        $indexName = $this->getDirectoryIndexFile(
```

2023-07-14 14:14 UTC, linawolf commented
@jaapio please have another look

2023-07-14 14:15 UTC, linawolf commented
@jaapio I applied all suggested changes, please have another look

2023-07-14 14:17 UTC, jaapio approved these changes

2023-07-14 14:17 UTC, merged