[FEATURE] Introduce table directive
phpDocumentor/guides pull request #576
Opened 2023-09-03 10:27 UTC by linawolf

2023-09-04 21:02 UTC, jaapio requested changes

2023-09-07 06:15 UTC, linawolf commented on packages/guides/resources/template/html/body/table.html.twig
> +                {% endif %}
This would not catch the width being 0 or smaller?

2023-09-07 06:16 UTC, linawolf commented on packages/guides/src/Nodes/AbstractNode.php
> +    public function withDefaultOptions(array $options): Node
Yes but that would be less clear?

2023-09-08 16:25 UTC, linawolf commented on packages/guides/resources/template/html/body/table.html.twig
> +{% endif %}
done

2023-09-08 16:26 UTC, linawolf commented
@jaapio please have another look at my answers and solutions

2023-09-08 19:40 UTC, jaapio commented on packages/guides/src/Nodes/AbstractNode.php
> +    public function withDefaultOptions(array $options): Node
The default makes me confused, I suggest, that we rename this to appendOptions. So it's clear that it are not defaults.

2023-09-09 11:45 UTC, jaapio approved these changes

2023-09-09 11:47 UTC, merged